#!/usr/bin/bash

export SLURM_JOB_NAME=SendAllArrayJob
export SLURM_JOB_GROUP=is.grp
export SLURM_JOB_STATE=COMPLETED
export SLURM_ARRAY_JOB_ID=1051491
export SLURM_JOB_WORK_DIR=/users/petar.jager
export SLURM_JOB_MAIL_TYPE=Ended
export SLURM_JOBID=1051492
export SLURM_ARRAY_TASK_ID=0
export SLURM_JOB_RUN_TIME=00:00:30
export SLURM_ARRAY_TASK_COUNT=6
export SLURM_JOB_EXIT_CODE2=0:0
export SLURM_JOB_DERIVED_EC=0
export SLURM_JOB_ID=1051492
export SLURM_JOB_USER=petar.jager
export SLURM_ARRAY_TASK_MAX=5
export SLURM_JOB_EXIT_CODE=0
export SLURM_JOB_UID=58546
export SLURM_JOB_NODELIST=stg-c2-0
export SLURM_ARRAY_TASK_MIN=0
export SLURM_JOB_STDIN=/dev/null
export SLURM_ARRAY_TASK_STEP=1
export SLURM_JOB_EXIT_CODE_MAX=0
export SLURM_JOB_GID=1999
export SLURM_CLUSTER_NAME=clip
export SLURM_JOB_PARTITION=c
export SLURM_JOB_ACCOUNT=hpc
