
# if specified; append logs to this file; else; dump to stderr
#
logfile = "/tmp/goslmailer.log"

# default connector to be used for message delivery for receivers without full 'connector:user' specification
#
defaultconnector = "msteams"

# enable/disable hints generation
# ToBeImplemented, hints now permanently enabled
#
#disableHints = 1

[binpaths]
sacct = "/usr/bin/sacct"
sstat = "/usr/bin/sstat"

# map of connector configurations
#
[connectors]

# each connector has it's own map of config attributes
#
[connectors.msteams]
name = "dev channel"                         # unused
spoolDir = "/tmp"                            # see below.
renderToFile = "yes"                         # if "yes"; dump rendered templates to working dir; else if "spool"; dump to spoolDir; else; send to teams url
url = "https://msteams/webhook/url"          # ms teams webhook url
adaptiveCardTemplate = "/path/template.json" # full path to adaptive card template file
useLookup = "GECOS"                          # which function from lookup package the connector uses to map cmdline userid to end-system userid

[connectors.mailto]
name = "original slurm mail functionality, extended."
mailCmd = "/usr/bin/mutt"
mailCmdParams = "-s \"Job {{ .SlurmEnvironment.SLURM_JOB_ID }} ({{ .SlurmEnvironment.SLURM_JOB_NAME }}) {{ .SlurmEnvironment.SLURM_JOB_MAIL_TYPE }}\""
mailTemplate = "/etc/slurm/mailTemplate.tmpl"    # message body template
mailFormat = "HTML"                              # `HTML` or `text` (can use telegram html in templates/)
allowList = ".+@(imp|imba.oeaw|gmi.oeaw).ac.at"
blockList = ""                                    # unused
    
[connectors.telegram]
name = "telegram bot connector"
url = ""
token = "PasteHereTelegramBotToken"
renderToFile = "no"
spoolDir = "/tmp/telegramgobs"
messageTemplate = "/etc/slurm/telegramTemplate.md"
useLookup = "no"
format = "MarkdownV2"

[connectors.matrix]
username = "@myuser:matrix.org"
token = "syt_dGRpZG9ib3QXXXXXXXEyQMBEmvOVp_10Jm93"
homeserver = "matrix.org"
template = "/path/to/matrix_template.md"

# fictitious "textfile" connector, package code for it doesn't exist, implementation left as the exercise for the reader
[connectors.textfile]
path = "/tmp"
  
# map of qos names with their respective time limit (seconds)
# used to generate hints, if hints are disabled, you can remove this from config
[qosmap]
RAPID = 3600
SHORT = 28800
MEDIUM = 172800
LONG = 1209600