init:
  test_readme: '${twd}/README.md'

defaults:
  message: "Running test $i from $twd"
  systempaths:
    - $bwd

pipeline:

  print_welcome:
    description: "Current test"
    action: workflow:print
    style: 1

  deploy_conf_files:
    action: storage:copy
    source:
      URL: $twd/conf
    dest:
      URL: /tmp

  deploy_sacct_files:
    action: storage:copy
    source:
      URL: $twd/sacct
    dest:
      URL: /tmp

  run_goslmailer:
    action: exec:run
    checkError: true
    env:
      GOSLMAILER_CONF: /tmp/goslmailer.conf
    commands: 
      - source $twd/slurm_env/slurmenv.sh
      - goslmailer -s "slurm job x" pja

  test_assert_goslmailer:
    action: validator:assert
    expect: 
      - '/Deposit gob OK!/'
    actual: 
      - $run_goslmailer.Output

  run_gobler:
    action: process:start
    watch: true
    immuneToHangups: true
    command: gobler -c /tmp/gobler.conf
    timeoutMs: 5000

  run_sleep:
    action: exec:run
    checkError: true
    commands: 
      - sleep 5

  stop_gobler:
    action: process:stop
    pid: $run_gobler.Pid

  # https://github.com/viant/assertly#validation
  test_assert_gobler:
    action: validator:assert
    expect: 
      - '~/Send successful to file: rendered-\d*-pja-/'
      - '~/SENDER msteams#\d: Gob deleted/'
    actual: 
      - $run_gobler.Stdout
      - $run_gobler.Stdout
