name: Build_on_tag

on:
  push:
    tags:
      - v**
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: make test

    - name: Build
      run: make build
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: goslmailer-${{ github.ref_name }}
        path: |
          goslmailer
          gobler
          ./cmd/goslmailer/adaptive_card_template.json
