name: Build_on_tag

on:
  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Prepare SSH for endly
      run: |
        mkdir ~/.secret
        mkdir ~/.ssh
        touch ~/.ssh/authorized_keys
        chmod 600 ~/.ssh/authorized_keys
        ssh-keygen -t ed25519 -f id_rsa -P "" -f ~/.secret/id_rsa
        cat ~/.secret/id_rsa.pub >>  ~/.ssh/authorized_keys
        echo "set enable-bracketed-paste off" >> ~/.inputrc
        cat >>~/.ssh/config <<END
        Host localhost
          IdentityFile ~/.secret/id_rsa
          StrictHostKeyChecking no
        END

    - name: Test
      run: make test

    - name: Build
      run: make build -e version=${{ github.sha }}

    - name: Get Endly
      run: make get_endly

    - name: Run E2E tests
      run: make test_endly

    - name: Install
      run: make install -e version=${{ github.sha }}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: goslmailer-${{ github.sha }}
        path: build/goslmailer-${{ github.sha }}/
