name: Go

on: workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: make test

    - name: Build
      run: make build -e version=${{ github.ref_name }}

    - name: Install
      run: make install -e version=${{ github.ref_name }}
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: goslmailer-${{ github.ref_name }}
        path: goslmailer-${{ github.ref_name }}/
